print("================================")
print("       WELCOME APP - V2")
print("================================")

name = input("Enter your name: ")
course = input("Enter your course: ")
year = input("Enter your year level: ")

print("\n--------------------------------")
print("Student Information")
print("--------------------------------")
print("Name  :", name)
print("Course:", course)
print("Year  :", year)
print("--------------------------------")
print("Welcome,", name + "!")
print("Thank you for using our app.")